// TODO: insanity? pollutes auto-complete? In JS, could be done with proxy objects v4.wzyx style
import { vec2, vec3, vec4 } from './vecmath.js'
// vec2 swizzle functions
export const xx = (v) => vec2(v.x, v.x)
export const xy = (v) => vec2(v.x, v.y)
export const yx = (v) => vec2(v.y, v.x)
export const yy = (v) => vec2(v.y, v.y)
// vec3 swizzle functions
export const xxx = (v) => vec3(v.x, v.x, v.x)
export const xxy = (v) => vec3(v.x, v.x, v.y)
export const xxz = (v) => vec3(v.x, v.x, v.z)
export const xyx = (v) => vec3(v.x, v.y, v.x)
export const xyy = (v) => vec3(v.x, v.y, v.y)
export const xyz = (v) => vec3(v.x, v.y, v.z)
export const xzx = (v) => vec3(v.x, v.z, v.x)
export const xzy = (v) => vec3(v.x, v.z, v.y)
export const xzz = (v) => vec3(v.x, v.z, v.z)
export const yxx = (v) => vec3(v.y, v.x, v.x)
export const yxy = (v) => vec3(v.y, v.x, v.y)
export const yxz = (v) => vec3(v.y, v.x, v.z)
export const yyx = (v) => vec3(v.y, v.y, v.x)
export const yyy = (v) => vec3(v.y, v.y, v.y)
export const yyz = (v) => vec3(v.y, v.y, v.z)
export const yzx = (v) => vec3(v.y, v.z, v.x)
export const yzy = (v) => vec3(v.y, v.z, v.y)
export const yzz = (v) => vec3(v.y, v.z, v.z)
export const zxx = (v) => vec3(v.z, v.x, v.x)
export const zxy = (v) => vec3(v.z, v.x, v.y)
export const zxz = (v) => vec3(v.z, v.x, v.z)
export const zyx = (v) => vec3(v.z, v.y, v.x)
export const zyy = (v) => vec3(v.z, v.y, v.y)
export const zyz = (v) => vec3(v.z, v.y, v.z)
export const zzx = (v) => vec3(v.z, v.z, v.x)
export const zzy = (v) => vec3(v.z, v.z, v.y)
export const zzz = (v) => vec3(v.z, v.z, v.z)
// vec4 swizzle functions
export const xxxx = (v) => vec4(v.x, v.x, v.x, v.x)
export const xxxy = (v) => vec4(v.x, v.x, v.x, v.y)
export const xxxz = (v) => vec4(v.x, v.x, v.x, v.z)
export const xxxw = (v) => vec4(v.x, v.x, v.x, v.w)
export const xxyx = (v) => vec4(v.x, v.x, v.y, v.x)
export const xxyy = (v) => vec4(v.x, v.x, v.y, v.y)
export const xxyz = (v) => vec4(v.x, v.x, v.y, v.z)
export const xxyw = (v) => vec4(v.x, v.x, v.y, v.w)
export const xxzx = (v) => vec4(v.x, v.x, v.z, v.x)
export const xxzy = (v) => vec4(v.x, v.x, v.z, v.y)
export const xxzz = (v) => vec4(v.x, v.x, v.z, v.z)
export const xxzw = (v) => vec4(v.x, v.x, v.z, v.w)
export const xxwx = (v) => vec4(v.x, v.x, v.w, v.x)
export const xxwy = (v) => vec4(v.x, v.x, v.w, v.y)
export const xxwz = (v) => vec4(v.x, v.x, v.w, v.z)
export const xxww = (v) => vec4(v.x, v.x, v.w, v.w)
export const xyxx = (v) => vec4(v.x, v.y, v.x, v.x)
export const xyxy = (v) => vec4(v.x, v.y, v.x, v.y)
export const xyxz = (v) => vec4(v.x, v.y, v.x, v.z)
export const xyxw = (v) => vec4(v.x, v.y, v.x, v.w)
export const xyyx = (v) => vec4(v.x, v.y, v.y, v.x)
export const xyyy = (v) => vec4(v.x, v.y, v.y, v.y)
export const xyyz = (v) => vec4(v.x, v.y, v.y, v.z)
export const xyyw = (v) => vec4(v.x, v.y, v.y, v.w)
export const xyzx = (v) => vec4(v.x, v.y, v.z, v.x)
export const xyzy = (v) => vec4(v.x, v.y, v.z, v.y)
export const xyzz = (v) => vec4(v.x, v.y, v.z, v.z)
export const xyzw = (v) => vec4(v.x, v.y, v.z, v.w)
export const xywx = (v) => vec4(v.x, v.y, v.w, v.x)
export const xywy = (v) => vec4(v.x, v.y, v.w, v.y)
export const xywz = (v) => vec4(v.x, v.y, v.w, v.z)
export const xyww = (v) => vec4(v.x, v.y, v.w, v.w)
export const xzxx = (v) => vec4(v.x, v.z, v.x, v.x)
export const xzxy = (v) => vec4(v.x, v.z, v.x, v.y)
export const xzxz = (v) => vec4(v.x, v.z, v.x, v.z)
export const xzxw = (v) => vec4(v.x, v.z, v.x, v.w)
export const xzyx = (v) => vec4(v.x, v.z, v.y, v.x)
export const xzyy = (v) => vec4(v.x, v.z, v.y, v.y)
export const xzyz = (v) => vec4(v.x, v.z, v.y, v.z)
export const xzyw = (v) => vec4(v.x, v.z, v.y, v.w)
export const xzzx = (v) => vec4(v.x, v.z, v.z, v.x)
export const xzzy = (v) => vec4(v.x, v.z, v.z, v.y)
export const xzzz = (v) => vec4(v.x, v.z, v.z, v.z)
export const xzzw = (v) => vec4(v.x, v.z, v.z, v.w)
export const xzwx = (v) => vec4(v.x, v.z, v.w, v.x)
export const xzwy = (v) => vec4(v.x, v.z, v.w, v.y)
export const xzwz = (v) => vec4(v.x, v.z, v.w, v.z)
export const xzww = (v) => vec4(v.x, v.z, v.w, v.w)
export const xwxx = (v) => vec4(v.x, v.w, v.x, v.x)
export const xwxy = (v) => vec4(v.x, v.w, v.x, v.y)
export const xwxz = (v) => vec4(v.x, v.w, v.x, v.z)
export const xwxw = (v) => vec4(v.x, v.w, v.x, v.w)
export const xwyx = (v) => vec4(v.x, v.w, v.y, v.x)
export const xwyy = (v) => vec4(v.x, v.w, v.y, v.y)
export const xwyz = (v) => vec4(v.x, v.w, v.y, v.z)
export const xwyw = (v) => vec4(v.x, v.w, v.y, v.w)
export const xwzx = (v) => vec4(v.x, v.w, v.z, v.x)
export const xwzy = (v) => vec4(v.x, v.w, v.z, v.y)
export const xwzz = (v) => vec4(v.x, v.w, v.z, v.z)
export const xwzw = (v) => vec4(v.x, v.w, v.z, v.w)
export const xwwx = (v) => vec4(v.x, v.w, v.w, v.x)
export const xwwy = (v) => vec4(v.x, v.w, v.w, v.y)
export const xwwz = (v) => vec4(v.x, v.w, v.w, v.z)
export const xwww = (v) => vec4(v.x, v.w, v.w, v.w)
export const yxxx = (v) => vec4(v.y, v.x, v.x, v.x)
export const yxxy = (v) => vec4(v.y, v.x, v.x, v.y)
export const yxxz = (v) => vec4(v.y, v.x, v.x, v.z)
export const yxxw = (v) => vec4(v.y, v.x, v.x, v.w)
export const yxyx = (v) => vec4(v.y, v.x, v.y, v.x)
export const yxyy = (v) => vec4(v.y, v.x, v.y, v.y)
export const yxyz = (v) => vec4(v.y, v.x, v.y, v.z)
export const yxyw = (v) => vec4(v.y, v.x, v.y, v.w)
export const yxzx = (v) => vec4(v.y, v.x, v.z, v.x)
export const yxzy = (v) => vec4(v.y, v.x, v.z, v.y)
export const yxzz = (v) => vec4(v.y, v.x, v.z, v.z)
export const yxzw = (v) => vec4(v.y, v.x, v.z, v.w)
export const yxwx = (v) => vec4(v.y, v.x, v.w, v.x)
export const yxwy = (v) => vec4(v.y, v.x, v.w, v.y)
export const yxwz = (v) => vec4(v.y, v.x, v.w, v.z)
export const yxww = (v) => vec4(v.y, v.x, v.w, v.w)
export const yyxx = (v) => vec4(v.y, v.y, v.x, v.x)
export const yyxy = (v) => vec4(v.y, v.y, v.x, v.y)
export const yyxz = (v) => vec4(v.y, v.y, v.x, v.z)
export const yyxw = (v) => vec4(v.y, v.y, v.x, v.w)
export const yyyx = (v) => vec4(v.y, v.y, v.y, v.x)
export const yyyy = (v) => vec4(v.y, v.y, v.y, v.y)
export const yyyz = (v) => vec4(v.y, v.y, v.y, v.z)
export const yyyw = (v) => vec4(v.y, v.y, v.y, v.w)
export const yyzx = (v) => vec4(v.y, v.y, v.z, v.x)
export const yyzy = (v) => vec4(v.y, v.y, v.z, v.y)
export const yyzz = (v) => vec4(v.y, v.y, v.z, v.z)
export const yyzw = (v) => vec4(v.y, v.y, v.z, v.w)
export const yywx = (v) => vec4(v.y, v.y, v.w, v.x)
export const yywy = (v) => vec4(v.y, v.y, v.w, v.y)
export const yywz = (v) => vec4(v.y, v.y, v.w, v.z)
export const yyww = (v) => vec4(v.y, v.y, v.w, v.w)
export const yzxx = (v) => vec4(v.y, v.z, v.x, v.x)
export const yzxy = (v) => vec4(v.y, v.z, v.x, v.y)
export const yzxz = (v) => vec4(v.y, v.z, v.x, v.z)
export const yzxw = (v) => vec4(v.y, v.z, v.x, v.w)
export const yzyx = (v) => vec4(v.y, v.z, v.y, v.x)
export const yzyy = (v) => vec4(v.y, v.z, v.y, v.y)
export const yzyz = (v) => vec4(v.y, v.z, v.y, v.z)
export const yzyw = (v) => vec4(v.y, v.z, v.y, v.w)
export const yzzx = (v) => vec4(v.y, v.z, v.z, v.x)
export const yzzy = (v) => vec4(v.y, v.z, v.z, v.y)
export const yzzz = (v) => vec4(v.y, v.z, v.z, v.z)
export const yzzw = (v) => vec4(v.y, v.z, v.z, v.w)
export const yzwx = (v) => vec4(v.y, v.z, v.w, v.x)
export const yzwy = (v) => vec4(v.y, v.z, v.w, v.y)
export const yzwz = (v) => vec4(v.y, v.z, v.w, v.z)
export const yzww = (v) => vec4(v.y, v.z, v.w, v.w)
export const ywxx = (v) => vec4(v.y, v.w, v.x, v.x)
export const ywxy = (v) => vec4(v.y, v.w, v.x, v.y)
export const ywxz = (v) => vec4(v.y, v.w, v.x, v.z)
export const ywxw = (v) => vec4(v.y, v.w, v.x, v.w)
export const ywyx = (v) => vec4(v.y, v.w, v.y, v.x)
export const ywyy = (v) => vec4(v.y, v.w, v.y, v.y)
export const ywyz = (v) => vec4(v.y, v.w, v.y, v.z)
export const ywyw = (v) => vec4(v.y, v.w, v.y, v.w)
export const ywzx = (v) => vec4(v.y, v.w, v.z, v.x)
export const ywzy = (v) => vec4(v.y, v.w, v.z, v.y)
export const ywzz = (v) => vec4(v.y, v.w, v.z, v.z)
export const ywzw = (v) => vec4(v.y, v.w, v.z, v.w)
export const ywwx = (v) => vec4(v.y, v.w, v.w, v.x)
export const ywwy = (v) => vec4(v.y, v.w, v.w, v.y)
export const ywwz = (v) => vec4(v.y, v.w, v.w, v.z)
export const ywww = (v) => vec4(v.y, v.w, v.w, v.w)
export const zxxx = (v) => vec4(v.z, v.x, v.x, v.x)
export const zxxy = (v) => vec4(v.z, v.x, v.x, v.y)
export const zxxz = (v) => vec4(v.z, v.x, v.x, v.z)
export const zxxw = (v) => vec4(v.z, v.x, v.x, v.w)
export const zxyx = (v) => vec4(v.z, v.x, v.y, v.x)
export const zxyy = (v) => vec4(v.z, v.x, v.y, v.y)
export const zxyz = (v) => vec4(v.z, v.x, v.y, v.z)
export const zxyw = (v) => vec4(v.z, v.x, v.y, v.w)
export const zxzx = (v) => vec4(v.z, v.x, v.z, v.x)
export const zxzy = (v) => vec4(v.z, v.x, v.z, v.y)
export const zxzz = (v) => vec4(v.z, v.x, v.z, v.z)
export const zxzw = (v) => vec4(v.z, v.x, v.z, v.w)
export const zxwx = (v) => vec4(v.z, v.x, v.w, v.x)
export const zxwy = (v) => vec4(v.z, v.x, v.w, v.y)
export const zxwz = (v) => vec4(v.z, v.x, v.w, v.z)
export const zxww = (v) => vec4(v.z, v.x, v.w, v.w)
export const zyxx = (v) => vec4(v.z, v.y, v.x, v.x)
export const zyxy = (v) => vec4(v.z, v.y, v.x, v.y)
export const zyxz = (v) => vec4(v.z, v.y, v.x, v.z)
export const zyxw = (v) => vec4(v.z, v.y, v.x, v.w)
export const zyyx = (v) => vec4(v.z, v.y, v.y, v.x)
export const zyyy = (v) => vec4(v.z, v.y, v.y, v.y)
export const zyyz = (v) => vec4(v.z, v.y, v.y, v.z)
export const zyyw = (v) => vec4(v.z, v.y, v.y, v.w)
export const zyzx = (v) => vec4(v.z, v.y, v.z, v.x)
export const zyzy = (v) => vec4(v.z, v.y, v.z, v.y)
export const zyzz = (v) => vec4(v.z, v.y, v.z, v.z)
export const zyzw = (v) => vec4(v.z, v.y, v.z, v.w)
export const zywx = (v) => vec4(v.z, v.y, v.w, v.x)
export const zywy = (v) => vec4(v.z, v.y, v.w, v.y)
export const zywz = (v) => vec4(v.z, v.y, v.w, v.z)
export const zyww = (v) => vec4(v.z, v.y, v.w, v.w)
export const zzxx = (v) => vec4(v.z, v.z, v.x, v.x)
export const zzxy = (v) => vec4(v.z, v.z, v.x, v.y)
export const zzxz = (v) => vec4(v.z, v.z, v.x, v.z)
export const zzxw = (v) => vec4(v.z, v.z, v.x, v.w)
export const zzyx = (v) => vec4(v.z, v.z, v.y, v.x)
export const zzyy = (v) => vec4(v.z, v.z, v.y, v.y)
export const zzyz = (v) => vec4(v.z, v.z, v.y, v.z)
export const zzyw = (v) => vec4(v.z, v.z, v.y, v.w)
export const zzzx = (v) => vec4(v.z, v.z, v.z, v.x)
export const zzzy = (v) => vec4(v.z, v.z, v.z, v.y)
export const zzzz = (v) => vec4(v.z, v.z, v.z, v.z)
export const zzzw = (v) => vec4(v.z, v.z, v.z, v.w)
export const zzwx = (v) => vec4(v.z, v.z, v.w, v.x)
export const zzwy = (v) => vec4(v.z, v.z, v.w, v.y)
export const zzwz = (v) => vec4(v.z, v.z, v.w, v.z)
export const zzww = (v) => vec4(v.z, v.z, v.w, v.w)
export const zwxx = (v) => vec4(v.z, v.w, v.x, v.x)
export const zwxy = (v) => vec4(v.z, v.w, v.x, v.y)
export const zwxz = (v) => vec4(v.z, v.w, v.x, v.z)
export const zwxw = (v) => vec4(v.z, v.w, v.x, v.w)
export const zwyx = (v) => vec4(v.z, v.w, v.y, v.x)
export const zwyy = (v) => vec4(v.z, v.w, v.y, v.y)
export const zwyz = (v) => vec4(v.z, v.w, v.y, v.z)
export const zwyw = (v) => vec4(v.z, v.w, v.y, v.w)
export const zwzx = (v) => vec4(v.z, v.w, v.z, v.x)
export const zwzy = (v) => vec4(v.z, v.w, v.z, v.y)
export const zwzz = (v) => vec4(v.z, v.w, v.z, v.z)
export const zwzw = (v) => vec4(v.z, v.w, v.z, v.w)
export const zwwx = (v) => vec4(v.z, v.w, v.w, v.x)
export const zwwy = (v) => vec4(v.z, v.w, v.w, v.y)
export const zwwz = (v) => vec4(v.z, v.w, v.w, v.z)
export const zwww = (v) => vec4(v.z, v.w, v.w, v.w)
export const wxxx = (v) => vec4(v.w, v.x, v.x, v.x)
export const wxxy = (v) => vec4(v.w, v.x, v.x, v.y)
export const wxxz = (v) => vec4(v.w, v.x, v.x, v.z)
export const wxxw = (v) => vec4(v.w, v.x, v.x, v.w)
export const wxyx = (v) => vec4(v.w, v.x, v.y, v.x)
export const wxyy = (v) => vec4(v.w, v.x, v.y, v.y)
export const wxyz = (v) => vec4(v.w, v.x, v.y, v.z)
export const wxyw = (v) => vec4(v.w, v.x, v.y, v.w)
export const wxzx = (v) => vec4(v.w, v.x, v.z, v.x)
export const wxzy = (v) => vec4(v.w, v.x, v.z, v.y)
export const wxzz = (v) => vec4(v.w, v.x, v.z, v.z)
export const wxzw = (v) => vec4(v.w, v.x, v.z, v.w)
export const wxwx = (v) => vec4(v.w, v.x, v.w, v.x)
export const wxwy = (v) => vec4(v.w, v.x, v.w, v.y)
export const wxwz = (v) => vec4(v.w, v.x, v.w, v.z)
export const wxww = (v) => vec4(v.w, v.x, v.w, v.w)
export const wyxx = (v) => vec4(v.w, v.y, v.x, v.x)
export const wyxy = (v) => vec4(v.w, v.y, v.x, v.y)
export const wyxz = (v) => vec4(v.w, v.y, v.x, v.z)
export const wyxw = (v) => vec4(v.w, v.y, v.x, v.w)
export const wyyx = (v) => vec4(v.w, v.y, v.y, v.x)
export const wyyy = (v) => vec4(v.w, v.y, v.y, v.y)
export const wyyz = (v) => vec4(v.w, v.y, v.y, v.z)
export const wyyw = (v) => vec4(v.w, v.y, v.y, v.w)
export const wyzx = (v) => vec4(v.w, v.y, v.z, v.x)
export const wyzy = (v) => vec4(v.w, v.y, v.z, v.y)
export const wyzz = (v) => vec4(v.w, v.y, v.z, v.z)
export const wyzw = (v) => vec4(v.w, v.y, v.z, v.w)
export const wywx = (v) => vec4(v.w, v.y, v.w, v.x)
export const wywy = (v) => vec4(v.w, v.y, v.w, v.y)
export const wywz = (v) => vec4(v.w, v.y, v.w, v.z)
export const wyww = (v) => vec4(v.w, v.y, v.w, v.w)
export const wzxx = (v) => vec4(v.w, v.z, v.x, v.x)
export const wzxy = (v) => vec4(v.w, v.z, v.x, v.y)
export const wzxz = (v) => vec4(v.w, v.z, v.x, v.z)
export const wzxw = (v) => vec4(v.w, v.z, v.x, v.w)
export const wzyx = (v) => vec4(v.w, v.z, v.y, v.x)
export const wzyy = (v) => vec4(v.w, v.z, v.y, v.y)
export const wzyz = (v) => vec4(v.w, v.z, v.y, v.z)
export const wzyw = (v) => vec4(v.w, v.z, v.y, v.w)
export const wzzx = (v) => vec4(v.w, v.z, v.z, v.x)
export const wzzy = (v) => vec4(v.w, v.z, v.z, v.y)
export const wzzz = (v) => vec4(v.w, v.z, v.z, v.z)
export const wzzw = (v) => vec4(v.w, v.z, v.z, v.w)
export const wzwx = (v) => vec4(v.w, v.z, v.w, v.x)
export const wzwy = (v) => vec4(v.w, v.z, v.w, v.y)
export const wzwz = (v) => vec4(v.w, v.z, v.w, v.z)
export const wzww = (v) => vec4(v.w, v.z, v.w, v.w)
export const wwxx = (v) => vec4(v.w, v.w, v.x, v.x)
export const wwxy = (v) => vec4(v.w, v.w, v.x, v.y)
export const wwxz = (v) => vec4(v.w, v.w, v.x, v.z)
export const wwxw = (v) => vec4(v.w, v.w, v.x, v.w)
export const wwyx = (v) => vec4(v.w, v.w, v.y, v.x)
export const wwyy = (v) => vec4(v.w, v.w, v.y, v.y)
export const wwyz = (v) => vec4(v.w, v.w, v.y, v.z)
export const wwyw = (v) => vec4(v.w, v.w, v.y, v.w)
export const wwzx = (v) => vec4(v.w, v.w, v.z, v.x)
export const wwzy = (v) => vec4(v.w, v.w, v.z, v.y)
export const wwzz = (v) => vec4(v.w, v.w, v.z, v.z)
export const wwzw = (v) => vec4(v.w, v.w, v.z, v.w)
export const wwwx = (v) => vec4(v.w, v.w, v.w, v.x)
export const wwwy = (v) => vec4(v.w, v.w, v.w, v.y)
export const wwwz = (v) => vec4(v.w, v.w, v.w, v.z)
export const wwww = (v) => vec4(v.w, v.w, v.w, v.w)
